name: Sales Time Series Prediction

on: [push, pull_request]

permissions: write-all

jobs:
  train_and_publish_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Setup Remote For DVC
        run: |
          dvc remote add -d localremote /mnt/shared/dvcstore --force

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run DVC pipeline
        run: |
          dvc repro